"""empty message

Revision ID: f5c57a8948af
Revises: 
Create Date: 2020-10-13 15:41:25.058750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c57a8948af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.Column('proveedor', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('kg', sa.String(length=8), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta')
    # ### end Alembic commands ###
